[project]
name = "synthse"
version = "0.1.0"
description = "Local text-to-image generation pipeline for Software Engineering scenarios"
authors = [
    { name = "Antonio Nappi" },
    { name = "Luca Casillo" }
]
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
